project_id = "atjmbprryznwhwsinrtj"

[functions.send-business-order-notification]
verify_jwt = false

[functions.verify-admin]
verify_jwt = false

[functions.verify-token]
verify_jwt = false

[functions.notify-owner-order]
verify_jwt = false

[functions.telegram-poll]
verify_jwt = false