
const initialProducts = [
  // Aachar (Pickles)
  {
    id: 1,
    name: "Aam Aachar",
    category: "aachar",
    price: 299,
    image: "/images/mango-pickle.jpg",
    description: "Traditional raw mango pickle with authentic Rajasthani spices.",
    ingredients: ["Raw Mango", "Mustard Oil", "Spices"],
    isPopular: true,
  },
  {
    id: 2,
    name: "Aam Chunda",
    category: "aachar",
    price: 259,
    image: "/placeholder.svg",
    description: "Sweet and tangy grated mango pickle.",
    ingredients: ["Raw Mango", "Sugar", "Spices"],
  },
  {
    id: 3,
    name: "Aawla Aachar",
    category: "aachar",
    price: 279,
    image: "/placeholder.svg",
    description: "Nutritious Indian gooseberry pickle.",
    ingredients: ["Amla", "Oil", "Spices"],
  },
  {
    id: 4,
    name: "Selvat Aachar",
    category: "aachar",
    price: 269,
    image: "/placeholder.svg",
    description: "Traditional Selvat style pickle.",
    ingredients: ["Mixed Vegetables", "Oil", "Spices"],
  },
  {
    id: 5,
    name: "Nimbu Khatta",
    category: "aachar",
    price: 249,
    image: "/placeholder.svg",
    description: "Tangy lemon pickle.",
    ingredients: ["Lemon", "Oil", "Spices"],
  },
  {
    id: 6,
    name: "Nimbu Mitha",
    category: "aachar",
    price: 249,
    image: "/placeholder.svg",
    description: "Sweet and sour lemon pickle.",
    ingredients: ["Lemon", "Sugar", "Spices"],
  },
  {
    id: 7,
    name: "Ker Aachar",
    category: "aachar",
    price: 289,
    image: "/placeholder.svg",
    description: "Traditional Ker berry pickle.",
    ingredients: ["Ker Berries", "Oil", "Spices"],
  },
  {
    id: 8,
    name: "Ker Sangari",
    category: "aachar",
    price: 299,
    image: "/placeholder.svg",
    description: "Classic Ker Sangari pickle.",
    ingredients: ["Ker", "Sangari", "Spices"],
  },
  {
    id: 9,
    name: "Dana Methi Aachar",
    category: "aachar",
    price: 259,
    image: "/placeholder.svg",
    description: "Fenugreek seeds pickle.",
    ingredients: ["Fenugreek Seeds", "Oil", "Spices"],
  },
  {
    id: 10,
    name: "Mix Aachar",
    category: "aachar",
    price: 279,
    image: "/placeholder.svg",
    description: "Mixed vegetable pickle.",
    ingredients: ["Mixed Vegetables", "Oil", "Spices"],
  },
  {
    id: 11,
    name: "Desi Mirch",
    category: "aachar",
    price: 269,
    image: "/placeholder.svg",
    description: "Traditional chili pickle.",
    ingredients: ["Local Chilies", "Oil", "Spices"],
  },
  {
    id: 12,
    name: "Aathana Lal Mirch",
    category: "aachar",
    price: 259,
    image: "/placeholder.svg",
    description: "Red chili pickle.",
    ingredients: ["Red Chilies", "Oil", "Spices"],
  },
  {
    id: 13,
    name: "Aathana Hari Mirch",
    category: "aachar",
    price: 259,
    image: "/placeholder.svg",
    description: "Green chili pickle.",
    ingredients: ["Green Chilies", "Oil", "Spices"],
  },
  {
    id: 14,
    name: "Hari Mirch Kuta",
    category: "aachar",
    price: 229,
    image: "/images/mirchi-pickle.jpg",
    description: "Ground green chili pickle.",
    ingredients: ["Green Chilies", "Spices", "Oil"],
    isPopular: true,
  },
  {
    id: 15,
    name: "Kathal Aachar",
    category: "aachar",
    price: 289,
    image: "/placeholder.svg",
    description: "Jackfruit pickle.",
    ingredients: ["Jackfruit", "Oil", "Spices"],
  },
  {
    id: 16,
    name: "Haldi Aachar",
    category: "aachar",
    price: 269,
    image: "/placeholder.svg",
    description: "Turmeric pickle.",
    ingredients: ["Fresh Turmeric", "Oil", "Spices"],
  },
  {
    id: 17,
    name: "Lassan Aachar",
    category: "aachar",
    price: 249,
    image: "/images/garlic-pickle.jpg",
    description: "Spicy garlic pickle.",
    ingredients: ["Garlic", "Oil", "Spices"],
    isPopular: true,
  },
  // Papad
  {
    id: 18,
    name: "Moong Lassan Papad",
    category: "papad",
    price: 199,
    image: "/placeholder.svg",
    description: "Moong dal papad with garlic flavor.",
    ingredients: ["Moong Dal", "Garlic", "Spices"],
  },
  {
    id: 19,
    name: "Moong Panjabi Papad",
    category: "papad",
    price: 189,
    image: "/placeholder.svg",
    description: "Punjabi style moong dal papad.",
    ingredients: ["Moong Dal", "Spices"],
  },
  {
    id: 20,
    name: "Chana Panjabi Papad",
    category: "papad",
    price: 179,
    image: "/placeholder.svg",
    description: "Punjabi style chickpea papad.",
    ingredients: ["Chickpea Flour", "Spices"],
  },
  {
    id: 21,
    name: "Sabudana Plain Papad",
    category: "papad",
    price: 169,
    image: "/placeholder.svg",
    description: "Plain sago papad.",
    ingredients: ["Sago", "Salt"],
  },
  {
    id: 22,
    name: "Aalo Bhagar Sabudana",
    category: "papad",
    price: 189,
    image: "/placeholder.svg",
    description: "Potato and sago papad.",
    ingredients: ["Sago", "Potato", "Spices"],
  },
  {
    id: 23,
    name: "Rice Papad",
    category: "papad",
    price: 159,
    image: "/images/rice-papad.jpg",
    description: "Traditional rice papad.",
    ingredients: ["Rice Flour", "Spices"],
  },
  {
    id: 24,
    name: "Potato Chips",
    category: "papad",
    price: 149,
    image: "/images/masala-papad.jpg",
    description: "Crispy hand-cut potato chips.",
    ingredients: ["Potato", "Oil", "Salt"],
    isPopular: true,
  },
  // Dehydrated Powders
  {
    id: 25,
    name: "Aawla Powder",
    category: "powder",
    price: 299,
    image: "/placeholder.svg",
    description: "Dehydrated amla powder.",
    ingredients: ["Dried Amla"],
  },
  {
    id: 26,
    name: "Aritha Powder",
    category: "powder",
    price: 249,
    image: "/placeholder.svg",
    description: "Natural hair cleanser powder.",
    ingredients: ["Dried Aritha"],
  },
  {
    id: 27,
    name: "Shikakai Powder",
    category: "powder",
    price: 269,
    image: "/placeholder.svg",
    description: "Natural hair care powder.",
    ingredients: ["Dried Shikakai"],
  },
  {
    id: 28,
    name: "Jamun Powder",
    category: "powder",
    price: 319,
    image: "/placeholder.svg",
    description: "Dehydrated jamun powder.",
    ingredients: ["Dried Jamun"],
  },
  {
    id: 29,
    name: "Beetroot Powder",
    category: "powder",
    price: 289,
    image: "/placeholder.svg",
    description: "Dehydrated beetroot powder.",
    ingredients: ["Dried Beetroot"],
  },
  {
    id: 30,
    name: "Dana Methi Powder",
    category: "powder",
    price: 249,
    image: "/placeholder.svg",
    description: "Fenugreek seed powder.",
    ingredients: ["Dried Fenugreek Seeds"],
  },
  {
    id: 31,
    name: "Mint Powder",
    category: "powder",
    price: 279,
    image: "/placeholder.svg",
    description: "Dehydrated mint powder.",
    ingredients: ["Dried Mint Leaves"],
  },
  // Namkeen
  {
    id: 32,
    name: "Big Bhakarwadi",
    category: "namkeen",
    price: 299,
    image: "/placeholder.svg",
    description: "Large spiral snack with spicy filling.",
    ingredients: ["Wheat Flour", "Spices", "Oil"],
  },
  {
    id: 33,
    name: "Jain Bhakarwadi",
    category: "namkeen",
    price: 289,
    image: "/placeholder.svg",
    description: "Jain-friendly spiral snack.",
    ingredients: ["Wheat Flour", "Jain Spices", "Oil"],
  },
  {
    id: 34,
    name: "Alsi Puri",
    category: "namkeen",
    price: 249,
    image: "/placeholder.svg",
    description: "Flaxseed crackers.",
    ingredients: ["Flaxseed", "Flour", "Spices"],
  },
  {
    id: 35,
    name: "Butter Chakoli",
    category: "namkeen",
    price: 269,
    image: "/placeholder.svg",
    description: "Butter-flavored spiral snack.",
    ingredients: ["Wheat Flour", "Butter", "Spices"],
  },
  {
    id: 36,
    name: "Mix Dal Chakoli",
    category: "namkeen",
    price: 259,
    image: "/placeholder.svg",
    description: "Mixed lentil spiral snack.",
    ingredients: ["Mixed Lentils", "Spices", "Oil"],
  },
  // Special Items
  {
    id: 37,
    name: "Wheat Kurodi",
    category: "special",
    price: 179,
    image: "/placeholder.svg",
    description: "Traditional wheat-based crunchy snack.",
    ingredients: ["Wheat Flour", "Spices"],
    isPopular: true,
  },
  {
    id: 38,
    name: "Wheat Sevai",
    category: "special",
    price: 169,
    image: "/placeholder.svg",
    description: "Traditional wheat vermicelli.",
    ingredients: ["Wheat Flour"],
  },
];

export default initialProducts;
