// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-products.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^4.4.3";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/list-products.ts
var list_products_default = defineTool({
  name: "list_products",
  title: "List products",
  description: "List Marwad Maratha products (pickles, papads, masalas) with optional category or name search.",
  inputSchema: {
    search: z.string().trim().optional().describe("Filter by product name (partial match)."),
    category: z.string().trim().optional().describe("Filter by category, e.g. 'pickles' or 'papad'."),
    only_available: z.boolean().optional().describe("Only return products currently in stock."),
    limit: z.number().int().min(1).max(100).optional().describe("Max rows to return (default 25).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, category, only_available, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("products").select("id,name,category,price,weight,description,is_available,is_popular").order("name").limit(limit ?? 25);
    if (search) query = query.ilike("name", `%${search}%`);
    if (category) query = query.eq("category", category);
    if (only_available) query = query.eq("is_available", true);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-orders.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^4.4.3";
var list_orders_default = defineTool2({
  name: "list_orders",
  title: "List orders",
  description: "List customer orders, newest first. Requires an admin account; other users receive no rows.",
  inputSchema: {
    order_status: z2.enum(["pending", "confirmed", "packed", "shipped", "delivered", "cancelled"]).optional().describe("Filter by fulfilment status."),
    payment_status: z2.string().trim().optional().describe("Filter by payment status, e.g. 'paid' or 'pending'."),
    search: z2.string().trim().optional().describe("Match order number, customer name, or phone."),
    limit: z2.number().int().min(1).max(100).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_status, payment_status, search, limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("orders").select(
      "id,order_number,customer_name,phone,city,total_amount,payment_method,payment_status,order_status,created_at"
    ).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (order_status) query = query.eq("order_status", order_status);
    if (payment_status) query = query.eq("payment_status", payment_status);
    if (search) {
      query = query.or(
        `order_number.ilike.%${search}%,customer_name.ilike.%${search}%,phone.ilike.%${search}%`
      );
    }
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { orders: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-order.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^4.4.3";
var get_order_default = defineTool3({
  name: "get_order",
  title: "Get order details",
  description: "Fetch one order by its order number (e.g. MM-2025-0042), including items, address and payment details. Admin only.",
  inputSchema: {
    order_number: z3.string().trim().min(3).describe("The order number, e.g. MM-2025-0042.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("orders").select("*").eq("order_number", order_number).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: `No order found for ${order_number}.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/update-order-status.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^4.4.3";
var update_order_status_default = defineTool4({
  name: "update_order_status",
  title: "Update order status",
  description: "Update the fulfilment status (and optionally the payment status) of an order. Admin only.",
  inputSchema: {
    order_number: z4.string().trim().min(3).describe("The order number, e.g. MM-2025-0042."),
    order_status: z4.enum(["pending", "confirmed", "packed", "shipped", "delivered", "cancelled"]).optional().describe("New fulfilment status."),
    payment_status: z4.enum(["pending", "awaiting_verification", "paid", "failed", "refunded"]).optional().describe("New payment status.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ order_number, order_status, payment_status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    if (!order_status && !payment_status) {
      return {
        content: [{ type: "text", text: "Provide order_status and/or payment_status." }],
        isError: true
      };
    }
    const patch = {};
    if (order_status) patch.order_status = order_status;
    if (payment_status) {
      patch.payment_status = payment_status;
      if (payment_status === "paid") {
        patch.verified_at = (/* @__PURE__ */ new Date()).toISOString();
        patch.verified_by = ctx.getUserEmail() ?? ctx.getUserId() ?? "mcp";
      }
    }
    const { data, error } = await supabaseForUser(ctx).from("orders").update(patch).eq("order_number", order_number).select("order_number,order_status,payment_status").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return {
        content: [{ type: "text", text: `No order updated \u2014 ${order_number} not found or not permitted.` }],
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { order: data }
    };
  }
});

// src/lib/mcp/tools/get-business-settings.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_business_settings_default = defineTool5({
  name: "get_business_settings",
  title: "Get business settings",
  description: "Read the storefront's business settings: contact details, shipping charges and whether orders are being accepted.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser(ctx).from("settings").select("business_name,phone,whatsapp,email,address,shipping_charge,free_shipping_above,is_accepting_orders").limit(1).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No settings row found." }], isError: true };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { settings: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "atjmbprryznwhwsinrtj";
var mcp_default = defineMcp({
  name: "marwad-maratha",
  title: "Marwad Maratha",
  version: "0.1.0",
  instructions: "Tools for the Marwad Maratha homemade pickle & papad store. Use `list_products` to browse the catalogue, `list_orders` and `get_order` to review customer orders, `update_order_status` to move an order along or confirm payment, and `get_business_settings` for contact and shipping configuration. Order tools require an admin account.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_products_default, list_orders_default, get_order_default, update_order_status_default, get_business_settings_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
