// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bbjtukueneekrzuieuxw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJianR1a3VlbmVla3J6dWlldXh3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMjkzODQsImV4cCI6MjA2MDcwNTM4NH0.jO5JL7VX4bzLQw7RK2R2tnp_-umrlc_LbgcTjxHbE1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);